### PR TITLE
use upstream LWJGL packages directly

### PR DESCRIPTION
**Pull request by euccastro**
This works for me for LWJGL version 3.1.1 in a linux 64-bit computer.  I haven't tried it in other platforms.

### CODE REVIEW

**Comment by euccastro** [comment]
The point of this PR is that with latest LWJGL and Leiningen you don't need to repackage the native dependencies any more.  You just need to declare each of them like so:

`                 [org.lwjgl/lwjgl   "3.1.1" :classifier "natives-linux" :native-prefix ""]`

The annoying part is that each LWJGL submodule has a main package and a dependencies package for each platform, so this would introduce lots of typing and repetition into :dependencies.  This PR builds the dependency list programmatically from the version number and the list of packages you want.

**Comment by rogerallen** [comment]
This looks really fantastic--thanks!  It may be a few days before I get to test this out myself, but at this point, I do plan on accepting this.

**Comment by rogerallen** [comment]
I've tested on Mac & it works for me, too.  

The proof will really be the test on windows.  For Mac & linux, LWJGL only supports 64-bit libraries, so our machines have a simple case to deal with.  

But, there is support for 32-bit libs on windows.  LWJGL still puts the 32 & 64-bit libraries  together in the same directory and I'm afraid that could cause issues on win32.  But, maybe the naming convention they follow will be enough?  I'm not sure I'll be able to test this properly as I'm no expert windows 64/32-bit library handling.

**Comment by rogerallen** [comment]
Tested on 64-bit Windows & it works.  I'd like to get someone to confirm 32-bit Windows works...

```
C:\Users\rallen\Documents\Devel\Clojure\hello_lwjgl>lein version
Leiningen 2.7.1 on Java 1.8.0_101 Java HotSpot(TM) 64-Bit Server VM
C:\Users\rallen\Documents\Devel\Clojure\hello_lwjgl>lein run alpha
Hello, Lightweight Java Game Library! V 3.1.1 build 16
Run example Alpha
OpenGL version: 4.5.0 NVIDIA 376.33
```

**Pull request merged**
